# Generated by Django 3.2.4 on 2021-06-25 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.CharField(default='#ffffff', max_length=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('notify', models.BooleanField(default=False)),
                ('notify_on', models.DateTimeField(blank=True, null=True)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weakly', 'Weakly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
